version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: berkeley_app
    volumes:
      - .:/berkeley_app
    ports:
      - "8000:8000"
  redis_db:
    image: redis:3.2.8
    ports:
      - "6379:6379"